#pragma config(Sensor, dgtl6,  buttonSTOP,     sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           MotorCLAW,     tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void stop_motors(int pop_time){
		motor[leftMotor]=0;
		motor[rightMotor]=0;
		wait1Msec(pop_time);
}
task main()
{
	while(1==1)

	{
		motor[rightMotor] = vexRT[Ch3];
		motor[leftMotor] = vexRT[Ch2];

		if(vexRT[Btn6U] == 1)
		{
			motor[MotorCLAW] = 127;
		}

		else if(vexRT[Btn6D] == 1)
		{
			motor[MotorCLAW] = -127;
		}
		else
	  {
	  	motor[motorCLAW] = 0;
		}
		if(vexRT[Btn5U] == 1)
	  {
	  	stop_motors(1000)
		}

	}

}





